Написать проект add-item-requests для Спринта №15
gityanizamovramil/java-shareit pull request #4
Opened 2022-11-02 12:24 UTC by gityanizamovramil

2022-11-02 16:23 UTC, eugene-lenkevich requested changes
Привет, Рамиль, спасибо за PR

В целом все гут :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2022-11-02 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBooker_IdAndStartIsAfter(Long userId, LocalDateTime start, Sort sort, PageRequest pageRequest); //future by booker id
Параметр sort не надо указывать отдельно, он уже есть в объекте PageRequest, только его и достаточно :)
Тут и ниже

2022-11-02 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0) throw new PaginationException("paging invalid");
Вот этот код создания объекта PageRequest повторяется несколько раз и по сути своей утилитарный, не лучше ли его выделить в отдельный статический метод и использовать его во всех сервисах :)

2022-11-02 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          switch (state) {
Если есть желание можешь попробовать применить паттерн "стратегия"

Возможно, именно для этого случая стратегия покажется избыточной (обработчики все в одну строчку), но попробовать самое то, к тому же в реальной жизни часто используется, так как часто в обработчике бывает нетривиальная логика и куча своих зависимостей :) 

Смысл такой. У тебя есть соответствие между состоянием и обработчиком этого состояния.
Можно сделать мапу
Map<String, BookingStateFetchStrategy>, где BookingStateFetchStrategy - который будут реализовывать обработчики состояния

или же, более простой вариант, в мапу засунуть методы сервиса, примерно так будет
Map<String, Supplier> handlers = ...
handlers.put("ALL", this::handleAllState) 

То есть, мы заменяем switch на поиск нужного обработчика через map :)

https://ravthiru.medium.com/strategy-design-pattern-with-in-spring-boot-application-2ff5a7486cd8

2022-11-02 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (repoItems.isEmpty()) return Collections.emptyList();
А точно нужна эта проверка?
Стрим ниже, в случае если ничего не найдено, вернет такой же пустой список, можешь проверить :)

2022-11-02 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .requestId(item.getRequest() != null ? item.getRequest().getId() : null)
`item.getRequest() != null ? item.getRequest().getId() : null`

Это кстати можно записать покороче, ну или в более функциональном стиле, вот так :)

`Optional.ofNullable(item.getRequest()).map(ItemRequest::getId).orElse(null)`

2022-11-02 16:23 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +            List<Item> items = itemRepository.findAllByRequest_Id(itemRequestDto.getId());
Вот смотри. В цикле мы лазаем в БД для каждого id, это не особо оптимально, гораздо оптимальней доставать все записи одним запросом. Для этого в метод можно передавать массив идентификаторов, например :)

2022-11-04 16:00 UTC, gityanizamovramil commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllByBooker_IdAndStartIsAfter(Long userId, LocalDateTime start, Sort sort, PageRequest pageRequest); //future by booker id
Исправил. В целом выделял отдельным параметром ввиду неочевидности наличия Sort в PageRequest и напоминания, что важно использовать нужный вид Direction.

2022-11-04 16:03 UTC, gityanizamovramil commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (from < 0) throw new PaginationException("paging invalid");
Исправил. Выделил код в отдельный утилитарный класс PageRequestManager. Туда же закинул создание Sort и проверки.

2022-11-04 16:08 UTC, gityanizamovramil commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          switch (state) {
Материал по ссылке изучил.
Сделал что-то похожее с использованием стратегий и фабрики, пришлось разделить на две подкатегории в зависимости от того, кто делает запрос (booker или item owner). В целом как ты и говорил получилось больше кода. Спасибо за интересное решение.
На счет второго варианта решения с использованием Map<String, Supplier> handlers = ... handlers.put("ALL", this::handleAllState) не до конца прояснил. Имеешь ввиду создать отдельный класс или внутри самого сервиса все это реализовать?

2022-11-04 16:11 UTC, gityanizamovramil commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (repoItems.isEmpty()) return Collections.emptyList();
Исправил. 
Объясню, почему здесь я использовал флаг. Я хотел вернуть пустой список сразу без прогона по всему кода метода в случаях когда БД вернет пустой список. Думаю, что так будет быстрее с точки зрения эффективности. Насколько это оправдано?

2022-11-04 16:16 UTC, gityanizamovramil commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .requestId(item.getRequest() != null ? item.getRequest().getId() : null)
Круто. Спасибо за интересный способ с использованием Optional. 
Еще хотелось бы узнать, что оптимальней или более разумно использовать тернарные операторы как у меня, или твой вариант с Optional?

2022-11-04 16:18 UTC, gityanizamovramil commented on src/main/java/ru/practicum/shareit/requests/ItemRequestServiceImpl.java
> +            List<Item> items = itemRepository.findAllByRequest_Id(itemRequestDto.getId());
Исправил. Создал дополнительный метод в интерфейсе и поправил сам код в сервисе. Получилось больше кода, с точки зрения взаимодействия с БД получилось лучше, согласен, спасибо.

2022-11-04 17:18 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>          switch (state) {
На самом деле тут можо и так и так. Главное - сам смысл всей затеи, убрать ветвление, то есть длинющую простыню кода.

2022-11-04 17:20 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (repoItems.isEmpty()) return Collections.emptyList();
Не стоит так заморачиваться, если бы там были дополнительные запросы в БД или по сети, то былобы оправдано, но тут всего лишь несколько операторов, влияние на производительность мизерное, а вот влияние на читаемость кода мождет быть заметным, чем меньше кода - тем лучше, а оптимизировать будем потом, на основе данных профилировщика :)

2022-11-04 17:22 UTC, eugene-lenkevich commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +                .requestId(item.getRequest() != null ? item.getRequest().getId() : null)
Да как хочешь на самом деле, дело личных предпочтений :)

2022-11-04 17:44 UTC, eugene-lenkevich approved these changes
Теперь все отлично, спасибо :)

Отлично, стратегия получилась, правда можно не руками заполнять мапу, а, например, собирать бины, реализующие определенный интерфейс и складывать их без перечисления конкретных реализаций. В том числе средствами спринга. Но это уж не критично  :)

https://stackoverflow.com/questions/40286047/spring-get-all-beans-of-certain-interface-and-type

2022-11-05 03:46 UTC, merged